"""
- market_cap - 0
- enterprise_value - 1
- shares_outstanding - 2
- current_price - 3
- target_price - 4
- eps - 5
- book_per_share - 6
- pe - 7
- pb - 8
- beta - 9
- volume - 10
- avg volume - 11
- ev/ebitda - 12
- recomm_mean - 13
- recomm_avg - 14
- div_yield - 15
- payout_ratio - 16
- next 5y growth - 17
- ROA - 18
- ROE - 19
- peg - 20
- ps - 21
"""

class TICKERS_TIME_DATA__TYPE__CONST:
    GROUP_BASIC = 100
    GROUP_INCOME_STATEMENT__ANNUAL = 200
    GROUP_CASH_FLOW_STATEMENT__ANNUAL = 300
    GROUP_BALANCE_SHEET__ANNUAL = 400
    GROUP_INCOME_STATEMENT__QUATERLY = 500
    GROUP_CASH_FLOW_STATEMENT__QUATERLY = 600
    GROUP_BALANCE_SHEET__QUATERLY = 700

    MARKET_CAP = GROUP_BASIC + 0
    ENTERPRISE_VALUE = GROUP_BASIC + 1
    SHARES_OUTSTANDING = GROUP_BASIC + 2
    PRICE = GROUP_BASIC + 3
    TARGET_PRICE = GROUP_BASIC + 4
    EPS = GROUP_BASIC + 5
    BOOK_PER_SHARE = GROUP_BASIC + 6
    PE = GROUP_BASIC + 7
    PB = GROUP_BASIC + 8
    BETA = GROUP_BASIC + 9
    VOLUME = GROUP_BASIC + 10
    VOLUME_AVG = GROUP_BASIC + 11
    EV_EBITDA = GROUP_BASIC + 12
    RECOMM_MEAN = GROUP_BASIC + 13
    RECOMM_COUNT = GROUP_BASIC + 14
    DIV_YIELD = GROUP_BASIC + 15
    PAYOUT_RATIO = GROUP_BASIC + 16
    GROWTH_5Y = GROUP_BASIC + 17
    ROA = GROUP_BASIC + 18
    ROE = GROUP_BASIC + 19
    PEG = GROUP_BASIC + 20
    PS = GROUP_BASIC + 21
    # INCOME_STATEMENT - ANNUAL ==========================
    TOTAL_REVENUE = GROUP_INCOME_STATEMENT__ANNUAL + 0
    GROSS_PROFIT = GROUP_INCOME_STATEMENT__ANNUAL + 1
    EBITDA = GROUP_INCOME_STATEMENT__ANNUAL + 2
    NET_INCOME = GROUP_INCOME_STATEMENT__ANNUAL + 3
    BASIC_EPS = GROUP_INCOME_STATEMENT__ANNUAL + 4
    # CASH_FLOW - ANNUAL =================================
    CASH_FLOW_CONTINUING_OPERATION = GROUP_CASH_FLOW_STATEMENT__ANNUAL + 0
    FCF = GROUP_CASH_FLOW_STATEMENT__ANNUAL + 1
    # BALANCE_SHEET - ANNUAL =============================
    TOTAL_DEBT = GROUP_BALANCE_SHEET__ANNUAL + 0
    LONG_TERM_DEBT = GROUP_BALANCE_SHEET__ANNUAL + 1
    CURRENT_LIABILITIES = GROUP_BALANCE_SHEET__ANNUAL + 2
    TOTAL_ASSETS = GROUP_BALANCE_SHEET__ANNUAL + 3
    CURRENT_ASSETS = GROUP_BALANCE_SHEET__ANNUAL + 4
    CASH = GROUP_BALANCE_SHEET__ANNUAL + 5
    TOTAL_LIABILITIES = GROUP_BALANCE_SHEET__ANNUAL + 6
    STOCKHOLDER_EQUITY = GROUP_BALANCE_SHEET__ANNUAL + 7
    # INCOME_STATEMENT - QUATERLY ==========================
    TOTAL_REVENUE_Q = GROUP_INCOME_STATEMENT__QUATERLY + 0
    GROSS_PROFIT_Q = GROUP_INCOME_STATEMENT__QUATERLY + 1
    EBITDA_Q = GROUP_INCOME_STATEMENT__QUATERLY + 2
    NET_INCOME_Q = GROUP_INCOME_STATEMENT__QUATERLY + 3
    BASIC_EPS_Q = GROUP_INCOME_STATEMENT__QUATERLY + 4
    # CASH_FLOW - QUATERLY =================================
    CASH_FLOW_CONTINUING_OPERATION_Q = GROUP_CASH_FLOW_STATEMENT__QUATERLY + 0
    FCF_Q = GROUP_CASH_FLOW_STATEMENT__QUATERLY + 1
    # BALANCE_SHEET - QUATERLY =============================
    TOTAL_DEBT_Q = GROUP_BALANCE_SHEET__QUATERLY + 0
    LONG_TERM_DEBT_Q = GROUP_BALANCE_SHEET__QUATERLY + 1
    CURRENT_LIABILITIES_Q = GROUP_BALANCE_SHEET__QUATERLY + 2
    TOTAL_ASSETS_Q = GROUP_BALANCE_SHEET__QUATERLY + 3
    CURRENT_ASSETS_Q = GROUP_BALANCE_SHEET__QUATERLY + 4
    CASH_Q = GROUP_BALANCE_SHEET__QUATERLY + 5
    TOTAL_LIABILITIES_Q = GROUP_BALANCE_SHEET__QUATERLY + 6
    STOCKHOLDER_EQUITY_Q = GROUP_BALANCE_SHEET__QUATERLY + 7

FUNDAMENTAL_NAME__TO_TYPE__ANNUAL = {
    "Total Revenue": TICKERS_TIME_DATA__TYPE__CONST.TOTAL_REVENUE,
    "Gross Profit": TICKERS_TIME_DATA__TYPE__CONST.GROSS_PROFIT,
    "EBITDA": TICKERS_TIME_DATA__TYPE__CONST.EBITDA,
    "Net Income": TICKERS_TIME_DATA__TYPE__CONST.NET_INCOME,
    "Basic EPS": TICKERS_TIME_DATA__TYPE__CONST.BASIC_EPS,
    "Cash Flow From Continuing Operating Activities": TICKERS_TIME_DATA__TYPE__CONST.CASH_FLOW_CONTINUING_OPERATION,
    "Free Cash Flow": TICKERS_TIME_DATA__TYPE__CONST.FCF,
    "Total Debt": TICKERS_TIME_DATA__TYPE__CONST.TOTAL_DEBT,
    "Long Term Debt": TICKERS_TIME_DATA__TYPE__CONST.LONG_TERM_DEBT,
    "Current Liabilities": TICKERS_TIME_DATA__TYPE__CONST.CURRENT_LIABILITIES,
    "Total Assets": TICKERS_TIME_DATA__TYPE__CONST.TOTAL_ASSETS,
    "Current Assets": TICKERS_TIME_DATA__TYPE__CONST.CURRENT_ASSETS,
    "Cash Cash Equivalents And Short Term Investments": TICKERS_TIME_DATA__TYPE__CONST.CASH,
    "Total Liabilities Net Minority Interest": TICKERS_TIME_DATA__TYPE__CONST.TOTAL_LIABILITIES,
    "Stockholders Equity": TICKERS_TIME_DATA__TYPE__CONST.STOCKHOLDER_EQUITY
}

FUNDAMENTAL_NAME__TO_TYPE__QUATERLY = {
    "Total Revenue": TICKERS_TIME_DATA__TYPE__CONST.TOTAL_REVENUE_Q,
    "Gross Profit": TICKERS_TIME_DATA__TYPE__CONST.GROSS_PROFIT_Q,
    "EBITDA": TICKERS_TIME_DATA__TYPE__CONST.EBITDA_Q,
    "Net Income": TICKERS_TIME_DATA__TYPE__CONST.NET_INCOME_Q,
    "Basic EPS": TICKERS_TIME_DATA__TYPE__CONST.BASIC_EPS_Q,
    "Cash Flow From Continuing Operating Activities": TICKERS_TIME_DATA__TYPE__CONST.CASH_FLOW_CONTINUING_OPERATION_Q,
    "Free Cash Flow": TICKERS_TIME_DATA__TYPE__CONST.FCF_Q,
    "Total Debt": TICKERS_TIME_DATA__TYPE__CONST.TOTAL_DEBT_Q,
    "Long Term Debt": TICKERS_TIME_DATA__TYPE__CONST.LONG_TERM_DEBT_Q,
    "Current Liabilities": TICKERS_TIME_DATA__TYPE__CONST.CURRENT_LIABILITIES_Q,
    "Total Assets": TICKERS_TIME_DATA__TYPE__CONST.TOTAL_ASSETS_Q,
    "Current Assets": TICKERS_TIME_DATA__TYPE__CONST.CURRENT_ASSETS_Q,
    "Cash Cash Equivalents And Short Term Investments": TICKERS_TIME_DATA__TYPE__CONST.CASH_Q,
    "Total Liabilities Net Minority Interest": TICKERS_TIME_DATA__TYPE__CONST.TOTAL_LIABILITIES_Q,
    "Stockholders Equity": TICKERS_TIME_DATA__TYPE__CONST.STOCKHOLDER_EQUITY_Q
}

TICKERS__TYPE_TO_COLUMN__DICT = {
    TICKERS_TIME_DATA__TYPE__CONST.MARKET_CAP : "market_cap",
    TICKERS_TIME_DATA__TYPE__CONST.PRICE : "price",
    TICKERS_TIME_DATA__TYPE__CONST.TARGET_PRICE : "target_price",
    TICKERS_TIME_DATA__TYPE__CONST.PE : "pe",
    TICKERS_TIME_DATA__TYPE__CONST.RECOMM_MEAN : "recomm_mean",
    TICKERS_TIME_DATA__TYPE__CONST.RECOMM_COUNT : "recomm_count",
    TICKERS_TIME_DATA__TYPE__CONST.DIV_YIELD : "div_yield",
    TICKERS_TIME_DATA__TYPE__CONST.PAYOUT_RATIO : "payout_ratio",
    TICKERS_TIME_DATA__TYPE__CONST.GROWTH_5Y : "growth_rate_5y"
}
